excerpt_separator: ""
rouge: true
markdown: kramdown
url: http://devenv.pl
name: DevEnv
header: DevEnv
description: "DevEnv - blog techniczny"
author: Adrian Piętka & Mateusz Książek
ga_domain: auto
ga_tracking_id: "UA-70075862-2"
authors:
  apietka:
    display_name: Adrian Piętka
    github: adrianpietka
    email: adrian@pietka.me
  mksiazek:
    display_name: Mateusz Książek
    github: mejt
    email: ksiazek.mate@gmail.com
gems:
  - jekyll-feed
feed:
  path: atom.xml
timezone: Europe/Warsaw
