excerpt_separator: ""
rouge: true
markdown: kramdown
url: http://devenv.pl
name: DevEnv
header: DevEnv
description: "DevEnv - blog techniczny"
author: Adrian Piętka & Mateusz Książek
ga_domain: 
ga_tracking_id:
authors:
  apietka:
    display_name: Adrian Piętka
    github: adrianpietka
  mksiazek:
    display_name: Mateusz Książek
    github: mejt
gems:
  - jekyll-feed
  - jekyll-tagging
feed:
  path: atom.xml
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
